[2025-03-30T22:05:21.658+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-30T22:05:21.711+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: import_ratings_to_database.load_ratings_to_sql manual__2025-03-30T22:05:19.074459+00:00 [queued]>
[2025-03-30T22:05:21.750+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: import_ratings_to_database.load_ratings_to_sql manual__2025-03-30T22:05:19.074459+00:00 [queued]>
[2025-03-30T22:05:21.757+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-30T22:05:21.828+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load_ratings_to_sql> on 2025-03-30 22:05:19.074459+00:00
[2025-03-30T22:05:21.853+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=344) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-30T22:05:21.858+0000] {standard_task_runner.py:72} INFO - Started process 352 to run task
[2025-03-30T22:05:21.859+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'import_ratings_to_database', 'load_ratings_to_sql', 'manual__2025-03-30T22:05:19.074459+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/etl_ratings.py', '--cfg-path', '/tmp/tmpfmsfohhb']
[2025-03-30T22:05:21.863+0000] {standard_task_runner.py:105} INFO - Job 34: Subtask load_ratings_to_sql
[2025-03-30T22:05:22.011+0000] {task_command.py:467} INFO - Running <TaskInstance: import_ratings_to_database.load_ratings_to_sql manual__2025-03-30T22:05:19.074459+00:00 [running]> on host 3947a336792d
[2025-03-30T22:05:22.264+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='azizjon' AIRFLOW_CTX_DAG_ID='import_ratings_to_database' AIRFLOW_CTX_TASK_ID='load_ratings_to_sql' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T22:05:19.074459+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-30T22:05:19.074459+00:00'
[2025-03-30T22:05:22.266+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-30T22:05:22.357+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-03-30T22:05:42.129+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-30T22:05:42.163+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-30T22:05:42.165+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=import_ratings_to_database, task_id=load_ratings_to_sql, run_id=manual__2025-03-30T22:05:19.074459+00:00, execution_date=20250330T220519, start_date=20250330T220521, end_date=20250330T220542
[2025-03-30T22:05:42.279+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-30T22:05:42.314+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T22:05:42.320+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
